//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AddOnFE_Facturatech.FacturatechWSdse {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DOCUMENTO-SOPORTE-FACTURATECHBinding", Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class DOCUMENTOSOPORTEFACTURATECH : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback uploadDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback documentStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadCUDSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DOCUMENTOSOPORTEFACTURATECH() {
            this.Url = global::AddOnFE_Facturatech.Properties.Settings.Default.AddOnFE_Facturatech_facturatechWSdse_DOCUMENTO_SOPORTE_FACTURATECH;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event uploadDocumentCompletedEventHandler uploadDocumentCompleted;
        
        /// <remarks/>
        public event documentStatusCompletedEventHandler documentStatusCompleted;
        
        /// <remarks/>
        public event downloadXMLCompletedEventHandler downloadXMLCompleted;
        
        /// <remarks/>
        public event downloadPDFCompletedEventHandler downloadPDFCompleted;
        
        /// <remarks/>
        public event downloadCUDSCompletedEventHandler downloadCUDSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws-dse.facturatech.co/uploadDocument", RequestNamespace="urn:https://ws-dse.facturatech.co/", ResponseNamespace="urn:https://ws-dse.facturatech.co/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public uploadResponse uploadDocument(string username, string password, string xmlBase64) {
            object[] results = this.Invoke("uploadDocument", new object[] {
                        username,
                        password,
                        xmlBase64});
            return ((uploadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void uploadDocumentAsync(string username, string password, string xmlBase64) {
            this.uploadDocumentAsync(username, password, xmlBase64, null);
        }
        
        /// <remarks/>
        public void uploadDocumentAsync(string username, string password, string xmlBase64, object userState) {
            if ((this.uploadDocumentOperationCompleted == null)) {
                this.uploadDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadDocumentOperationCompleted);
            }
            this.InvokeAsync("uploadDocument", new object[] {
                        username,
                        password,
                        xmlBase64}, this.uploadDocumentOperationCompleted, userState);
        }
        
        private void OnuploadDocumentOperationCompleted(object arg) {
            if ((this.uploadDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadDocumentCompleted(this, new uploadDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws-dse.facturatech.co/documentStatus", RequestNamespace="urn:https://ws-dse.facturatech.co/", ResponseNamespace="urn:https://ws-dse.facturatech.co/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public documentStatusResponse documentStatus(string username, string password, string transaccionID) {
            object[] results = this.Invoke("documentStatus", new object[] {
                        username,
                        password,
                        transaccionID});
            return ((documentStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void documentStatusAsync(string username, string password, string transaccionID) {
            this.documentStatusAsync(username, password, transaccionID, null);
        }
        
        /// <remarks/>
        public void documentStatusAsync(string username, string password, string transaccionID, object userState) {
            if ((this.documentStatusOperationCompleted == null)) {
                this.documentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OndocumentStatusOperationCompleted);
            }
            this.InvokeAsync("documentStatus", new object[] {
                        username,
                        password,
                        transaccionID}, this.documentStatusOperationCompleted, userState);
        }
        
        private void OndocumentStatusOperationCompleted(object arg) {
            if ((this.documentStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.documentStatusCompleted(this, new documentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws-dse.facturatech.co/downloadXML", RequestNamespace="urn:https://ws-dse.facturatech.co/", ResponseNamespace="urn:https://ws-dse.facturatech.co/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public downloadXMLResponse downloadXML(string username, string password, string prefix, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string number) {
            object[] results = this.Invoke("downloadXML", new object[] {
                        username,
                        password,
                        prefix,
                        number});
            return ((downloadXMLResponse)(results[0]));
        }
        
        /// <remarks/>
        public void downloadXMLAsync(string username, string password, string prefix, string number) {
            this.downloadXMLAsync(username, password, prefix, number, null);
        }
        
        /// <remarks/>
        public void downloadXMLAsync(string username, string password, string prefix, string number, object userState) {
            if ((this.downloadXMLOperationCompleted == null)) {
                this.downloadXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadXMLOperationCompleted);
            }
            this.InvokeAsync("downloadXML", new object[] {
                        username,
                        password,
                        prefix,
                        number}, this.downloadXMLOperationCompleted, userState);
        }
        
        private void OndownloadXMLOperationCompleted(object arg) {
            if ((this.downloadXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadXMLCompleted(this, new downloadXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws-dse.facturatech.co/downloadPDF", RequestNamespace="urn:https://ws-dse.facturatech.co/", ResponseNamespace="urn:https://ws-dse.facturatech.co/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public downloadPDFResponse downloadPDF(string username, string password, string prefix, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string number) {
            object[] results = this.Invoke("downloadPDF", new object[] {
                        username,
                        password,
                        prefix,
                        number});
            return ((downloadPDFResponse)(results[0]));
        }
        
        /// <remarks/>
        public void downloadPDFAsync(string username, string password, string prefix, string number) {
            this.downloadPDFAsync(username, password, prefix, number, null);
        }
        
        /// <remarks/>
        public void downloadPDFAsync(string username, string password, string prefix, string number, object userState) {
            if ((this.downloadPDFOperationCompleted == null)) {
                this.downloadPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadPDFOperationCompleted);
            }
            this.InvokeAsync("downloadPDF", new object[] {
                        username,
                        password,
                        prefix,
                        number}, this.downloadPDFOperationCompleted, userState);
        }
        
        private void OndownloadPDFOperationCompleted(object arg) {
            if ((this.downloadPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadPDFCompleted(this, new downloadPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws-dse.facturatech.co/downloadCUDSResponse", RequestNamespace="urn:https://ws-dse.facturatech.co/", ResponseNamespace="urn:https://ws-dse.facturatech.co/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public downloadCUDSResponse downloadCUDS(string username, string password, string prefix, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string number) {
            object[] results = this.Invoke("downloadCUDS", new object[] {
                        username,
                        password,
                        prefix,
                        number});
            return ((downloadCUDSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void downloadCUDSAsync(string username, string password, string prefix, string number) {
            this.downloadCUDSAsync(username, password, prefix, number, null);
        }
        
        /// <remarks/>
        public void downloadCUDSAsync(string username, string password, string prefix, string number, object userState) {
            if ((this.downloadCUDSOperationCompleted == null)) {
                this.downloadCUDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadCUDSOperationCompleted);
            }
            this.InvokeAsync("downloadCUDS", new object[] {
                        username,
                        password,
                        prefix,
                        number}, this.downloadCUDSOperationCompleted, userState);
        }
        
        private void OndownloadCUDSOperationCompleted(object arg) {
            if ((this.downloadCUDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadCUDSCompleted(this, new downloadCUDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class uploadResponse {
        
        private string codeField;
        
        private string transactionIDField;
        
        private string messageField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class downloadCUDSResponse {
        
        private string codeField;
        
        private string messageField;
        
        private string resourceDataField;
        
        private string messageErrorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                this.resourceDataField = value;
            }
        }
        
        /// <remarks/>
        public string messageError {
            get {
                return this.messageErrorField;
            }
            set {
                this.messageErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class downloadPDFResponse {
        
        private string codeField;
        
        private string documentBase64Field;
        
        private string messageField;
        
        private string messageErrorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string documentBase64 {
            get {
                return this.documentBase64Field;
            }
            set {
                this.documentBase64Field = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string messageError {
            get {
                return this.messageErrorField;
            }
            set {
                this.messageErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class downloadXMLResponse {
        
        private string codeField;
        
        private string documentBase64Field;
        
        private string messageField;
        
        private string messageErrorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string documentBase64 {
            get {
                return this.documentBase64Field;
            }
            set {
                this.documentBase64Field = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string messageError {
            get {
                return this.messageErrorField;
            }
            set {
                this.messageErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws-dse.facturatech.co/")]
    public partial class documentStatusResponse {
        
        private string codeField;
        
        private string documentBase64Field;
        
        private string messageField;
        
        private string messageErrorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string documentBase64 {
            get {
                return this.documentBase64Field;
            }
            set {
                this.documentBase64Field = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string messageError {
            get {
                return this.messageErrorField;
            }
            set {
                this.messageErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void uploadDocumentCompletedEventHandler(object sender, uploadDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uploadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uploadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void documentStatusCompletedEventHandler(object sender, documentStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class documentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal documentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void downloadXMLCompletedEventHandler(object sender, downloadXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public downloadXMLResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((downloadXMLResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void downloadPDFCompletedEventHandler(object sender, downloadPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public downloadPDFResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((downloadPDFResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void downloadCUDSCompletedEventHandler(object sender, downloadCUDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadCUDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadCUDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public downloadCUDSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((downloadCUDSResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591