//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AddOnFE_Facturatech.FacturatechWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SERVICES-FACTURATECHBinding", Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class SERVICESFACTURATECH : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FtechActionuploadInvoiceFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiondocumentStatusFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiondownloadXMLFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiondownloadPDFFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiongetCUFEFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiongetQRFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActiongetQRImageFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback FtechActionuploadInvoiceFileLayoutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SERVICESFACTURATECH() {
            this.Url = global::AddOnFE_Facturatech.Properties.Settings.Default.AddOnFE_Facturatech_FacturatechWS_SERVICES_FACTURATECH;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FtechActionuploadInvoiceFileCompletedEventHandler FtechActionuploadInvoiceFileCompleted;
        
        /// <remarks/>
        public event FtechActiondocumentStatusFileCompletedEventHandler FtechActiondocumentStatusFileCompleted;
        
        /// <remarks/>
        public event FtechActiondownloadXMLFileCompletedEventHandler FtechActiondownloadXMLFileCompleted;
        
        /// <remarks/>
        public event FtechActiondownloadPDFFileCompletedEventHandler FtechActiondownloadPDFFileCompleted;
        
        /// <remarks/>
        public event FtechActiongetCUFEFileCompletedEventHandler FtechActiongetCUFEFileCompleted;
        
        /// <remarks/>
        public event FtechActiongetQRFileCompletedEventHandler FtechActiongetQRFileCompleted;
        
        /// <remarks/>
        public event FtechActiongetQRImageFileCompletedEventHandler FtechActiongetQRImageFileCompleted;
        
        /// <remarks/>
        public event FtechActionuploadInvoiceFileLayoutCompletedEventHandler FtechActionuploadInvoiceFileLayoutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.uploadInvoiceFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_ws FtechActionuploadInvoiceFile(string username, string password, string xmlBase64) {
            object[] results = this.Invoke("FtechActionuploadInvoiceFile", new object[] {
                        username,
                        password,
                        xmlBase64});
            return ((response_ws)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActionuploadInvoiceFileAsync(string username, string password, string xmlBase64) {
            this.FtechActionuploadInvoiceFileAsync(username, password, xmlBase64, null);
        }
        
        /// <remarks/>
        public void FtechActionuploadInvoiceFileAsync(string username, string password, string xmlBase64, object userState) {
            if ((this.FtechActionuploadInvoiceFileOperationCompleted == null)) {
                this.FtechActionuploadInvoiceFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActionuploadInvoiceFileOperationCompleted);
            }
            this.InvokeAsync("FtechActionuploadInvoiceFile", new object[] {
                        username,
                        password,
                        xmlBase64}, this.FtechActionuploadInvoiceFileOperationCompleted, userState);
        }
        
        private void OnFtechActionuploadInvoiceFileOperationCompleted(object arg) {
            if ((this.FtechActionuploadInvoiceFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActionuploadInvoiceFileCompleted(this, new FtechActionuploadInvoiceFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.documentStatusFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_docs FtechActiondocumentStatusFile(string username, string password, string transaccionID) {
            object[] results = this.Invoke("FtechActiondocumentStatusFile", new object[] {
                        username,
                        password,
                        transaccionID});
            return ((response_docs)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiondocumentStatusFileAsync(string username, string password, string transaccionID) {
            this.FtechActiondocumentStatusFileAsync(username, password, transaccionID, null);
        }
        
        /// <remarks/>
        public void FtechActiondocumentStatusFileAsync(string username, string password, string transaccionID, object userState) {
            if ((this.FtechActiondocumentStatusFileOperationCompleted == null)) {
                this.FtechActiondocumentStatusFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiondocumentStatusFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiondocumentStatusFile", new object[] {
                        username,
                        password,
                        transaccionID}, this.FtechActiondocumentStatusFileOperationCompleted, userState);
        }
        
        private void OnFtechActiondocumentStatusFileOperationCompleted(object arg) {
            if ((this.FtechActiondocumentStatusFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiondocumentStatusFileCompleted(this, new FtechActiondocumentStatusFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.downloadXMLFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_xml FtechActiondownloadXMLFile(string username, string password, string prefijo, string folio) {
            object[] results = this.Invoke("FtechActiondownloadXMLFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio});
            return ((response_xml)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiondownloadXMLFileAsync(string username, string password, string prefijo, string folio) {
            this.FtechActiondownloadXMLFileAsync(username, password, prefijo, folio, null);
        }
        
        /// <remarks/>
        public void FtechActiondownloadXMLFileAsync(string username, string password, string prefijo, string folio, object userState) {
            if ((this.FtechActiondownloadXMLFileOperationCompleted == null)) {
                this.FtechActiondownloadXMLFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiondownloadXMLFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiondownloadXMLFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio}, this.FtechActiondownloadXMLFileOperationCompleted, userState);
        }
        
        private void OnFtechActiondownloadXMLFileOperationCompleted(object arg) {
            if ((this.FtechActiondownloadXMLFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiondownloadXMLFileCompleted(this, new FtechActiondownloadXMLFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.downloadPDFFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_pdf FtechActiondownloadPDFFile(string username, string password, string prefijo, string folio) {
            object[] results = this.Invoke("FtechActiondownloadPDFFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio});
            return ((response_pdf)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiondownloadPDFFileAsync(string username, string password, string prefijo, string folio) {
            this.FtechActiondownloadPDFFileAsync(username, password, prefijo, folio, null);
        }
        
        /// <remarks/>
        public void FtechActiondownloadPDFFileAsync(string username, string password, string prefijo, string folio, object userState) {
            if ((this.FtechActiondownloadPDFFileOperationCompleted == null)) {
                this.FtechActiondownloadPDFFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiondownloadPDFFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiondownloadPDFFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio}, this.FtechActiondownloadPDFFileOperationCompleted, userState);
        }
        
        private void OnFtechActiondownloadPDFFileOperationCompleted(object arg) {
            if ((this.FtechActiondownloadPDFFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiondownloadPDFFileCompleted(this, new FtechActiondownloadPDFFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.getCUFEFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_cufe FtechActiongetCUFEFile(string username, string password, string prefijo, string folio) {
            object[] results = this.Invoke("FtechActiongetCUFEFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio});
            return ((response_cufe)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiongetCUFEFileAsync(string username, string password, string prefijo, string folio) {
            this.FtechActiongetCUFEFileAsync(username, password, prefijo, folio, null);
        }
        
        /// <remarks/>
        public void FtechActiongetCUFEFileAsync(string username, string password, string prefijo, string folio, object userState) {
            if ((this.FtechActiongetCUFEFileOperationCompleted == null)) {
                this.FtechActiongetCUFEFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiongetCUFEFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiongetCUFEFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio}, this.FtechActiongetCUFEFileOperationCompleted, userState);
        }
        
        private void OnFtechActiongetCUFEFileOperationCompleted(object arg) {
            if ((this.FtechActiongetCUFEFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiongetCUFEFileCompleted(this, new FtechActiongetCUFEFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.getQRFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_qr FtechActiongetQRFile(string username, string password, string prefijo, string folio) {
            object[] results = this.Invoke("FtechActiongetQRFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio});
            return ((response_qr)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiongetQRFileAsync(string username, string password, string prefijo, string folio) {
            this.FtechActiongetQRFileAsync(username, password, prefijo, folio, null);
        }
        
        /// <remarks/>
        public void FtechActiongetQRFileAsync(string username, string password, string prefijo, string folio, object userState) {
            if ((this.FtechActiongetQRFileOperationCompleted == null)) {
                this.FtechActiongetQRFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiongetQRFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiongetQRFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio}, this.FtechActiongetQRFileOperationCompleted, userState);
        }
        
        private void OnFtechActiongetQRFileOperationCompleted(object arg) {
            if ((this.FtechActiongetQRFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiongetQRFileCompleted(this, new FtechActiongetQRFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.getQRImageFile", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_qr FtechActiongetQRImageFile(string username, string password, string prefijo, string folio) {
            object[] results = this.Invoke("FtechActiongetQRImageFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio});
            return ((response_qr)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActiongetQRImageFileAsync(string username, string password, string prefijo, string folio) {
            this.FtechActiongetQRImageFileAsync(username, password, prefijo, folio, null);
        }
        
        /// <remarks/>
        public void FtechActiongetQRImageFileAsync(string username, string password, string prefijo, string folio, object userState) {
            if ((this.FtechActiongetQRImageFileOperationCompleted == null)) {
                this.FtechActiongetQRImageFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActiongetQRImageFileOperationCompleted);
            }
            this.InvokeAsync("FtechActiongetQRImageFile", new object[] {
                        username,
                        password,
                        prefijo,
                        folio}, this.FtechActiongetQRImageFileOperationCompleted, userState);
        }
        
        private void OnFtechActiongetQRImageFileOperationCompleted(object arg) {
            if ((this.FtechActiongetQRImageFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActiongetQRImageFileCompleted(this, new FtechActiongetQRImageFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:https://ws.facturatech.co/v2/demo/#FtechAction.uploadInvoiceFileLayout", RequestNamespace="urn:https://ws.facturatech.co/v2/demo/", ResponseNamespace="urn:https://ws.facturatech.co/v2/demo/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public response_ws FtechActionuploadInvoiceFileLayout(string username, string password, string layout) {
            object[] results = this.Invoke("FtechActionuploadInvoiceFileLayout", new object[] {
                        username,
                        password,
                        layout});
            return ((response_ws)(results[0]));
        }
        
        /// <remarks/>
        public void FtechActionuploadInvoiceFileLayoutAsync(string username, string password, string layout) {
            this.FtechActionuploadInvoiceFileLayoutAsync(username, password, layout, null);
        }
        
        /// <remarks/>
        public void FtechActionuploadInvoiceFileLayoutAsync(string username, string password, string layout, object userState) {
            if ((this.FtechActionuploadInvoiceFileLayoutOperationCompleted == null)) {
                this.FtechActionuploadInvoiceFileLayoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFtechActionuploadInvoiceFileLayoutOperationCompleted);
            }
            this.InvokeAsync("FtechActionuploadInvoiceFileLayout", new object[] {
                        username,
                        password,
                        layout}, this.FtechActionuploadInvoiceFileLayoutOperationCompleted, userState);
        }
        
        private void OnFtechActionuploadInvoiceFileLayoutOperationCompleted(object arg) {
            if ((this.FtechActionuploadInvoiceFileLayoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FtechActionuploadInvoiceFileLayoutCompleted(this, new FtechActionuploadInvoiceFileLayoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_ws {
        
        private string codeField;
        
        private string successField;
        
        private string transaccionIDField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string transaccionID {
            get {
                return this.transaccionIDField;
            }
            set {
                this.transaccionIDField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_qr {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                this.resourceDataField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_cufe {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                this.resourceDataField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_pdf {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                this.resourceDataField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_xml {
        
        private string codeField;
        
        private string successField;
        
        private string resourceDataField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string resourceData {
            get {
                return this.resourceDataField;
            }
            set {
                this.resourceDataField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:https://ws.facturatech.co/v2/demo/")]
    public partial class response_docs {
        
        private string codeField;
        
        private string successField;
        
        private string statusField;
        
        private string errorField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActionuploadInvoiceFileCompletedEventHandler(object sender, FtechActionuploadInvoiceFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActionuploadInvoiceFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActionuploadInvoiceFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_ws Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_ws)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiondocumentStatusFileCompletedEventHandler(object sender, FtechActiondocumentStatusFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiondocumentStatusFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiondocumentStatusFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_docs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_docs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiondownloadXMLFileCompletedEventHandler(object sender, FtechActiondownloadXMLFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiondownloadXMLFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiondownloadXMLFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_xml Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_xml)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiondownloadPDFFileCompletedEventHandler(object sender, FtechActiondownloadPDFFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiondownloadPDFFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiondownloadPDFFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_pdf Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_pdf)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiongetCUFEFileCompletedEventHandler(object sender, FtechActiongetCUFEFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiongetCUFEFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiongetCUFEFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_cufe Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_cufe)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiongetQRFileCompletedEventHandler(object sender, FtechActiongetQRFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiongetQRFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiongetQRFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_qr Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_qr)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActiongetQRImageFileCompletedEventHandler(object sender, FtechActiongetQRImageFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActiongetQRImageFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActiongetQRImageFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_qr Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_qr)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FtechActionuploadInvoiceFileLayoutCompletedEventHandler(object sender, FtechActionuploadInvoiceFileLayoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FtechActionuploadInvoiceFileLayoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FtechActionuploadInvoiceFileLayoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public response_ws Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((response_ws)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591